# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE := third_party_WebKit_Source_WebKit_chromium_webkit_gyp
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_TAGS := optional
gyp_intermediate_dir := $(call local-intermediates-dir)
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared)

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES := \
	$(call intermediates-dir-for,GYP,third_party_WebKit_Source_core_webcore_gyp)/webcore.stamp \
	$(call intermediates-dir-for,STATIC_LIBRARIES,third_party_WebKit_Source_core_webcore_derived_gyp)/third_party_WebKit_Source_core_webcore_derived_gyp.a \
	$(call intermediates-dir-for,STATIC_LIBRARIES,skia_skia_gyp)/skia_skia_gyp.a \
	$(call intermediates-dir-for,GYP,third_party_icu_icuuc_gyp)/icuuc.stamp \
	$(call intermediates-dir-for,GYP,third_party_npapi_npapi_gyp)/npapi.stamp \
	$(call intermediates-dir-for,GYP,v8_tools_gyp_v8_gyp)/v8.stamp

GYP_GENERATED_OUTPUTS :=

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

LOCAL_GENERATED_SOURCES :=

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	third_party/WebKit/Source/core/platform/chromium/support/Platform.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebActiveGestureAnimation.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebAudioBus.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebCursorInfo.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebData.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebDeviceMotionData.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebFloatQuad.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebHTTPBody.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebHTTPLoadInfo.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebMediaConstraints.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebMediaStream.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebMediaStreamSource.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebMediaStreamSourcesRequest.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebMediaStreamTrack.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebPrerender.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebPrerenderingSupport.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebRTCConfiguration.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebRTCICECandidate.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebRTCSessionDescription.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebRTCSessionDescriptionRequest.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebRTCStatsRequest.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebRTCStatsResponse.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebRTCVoidRequest.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebScrollbarImpl.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebScrollbarThemeClientImpl.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebScrollbarThemeGeometryNative.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebSocketStreamError.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebSourceInfo.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebSpeechSynthesisUtterance.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebSpeechSynthesisVoice.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebSpeechSynthesizerClientImpl.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebThreadSafeData.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebTransformKeyframe.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebURL.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebURLError.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebURLRequest.cpp \
	third_party/WebKit/Source/core/platform/chromium/support/WebURLResponse.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ApplicationCacheHost.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/AssertMatchingEnums.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/AssociatedURLLoader.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/AsyncFileSystemChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/AsyncFileWriterChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/AutofillPopupMenuClient.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/BackForwardClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DateTimeChooserImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ChromeClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ColorChooserPopupUIController.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ColorChooserUIController.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/CompositionUnderlineVectorBuilder.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ContextFeaturesClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ContextMenuClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DatabaseObserver.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DeviceOrientationClientProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DOMUtilitiesPrivate.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DragClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DragScrollTimer.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/EditorClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/EventListenerWrapper.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ExternalDateTimeChooser.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ExternalPopupMenu.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/FindInPageCoordinates.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/FrameLoaderClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/GeolocationClientProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/GraphicsLayerFactoryChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebHelperPluginImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBCursorBackendProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBDatabaseBackendProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBFactoryBackendProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/InbandTextTrackPrivateImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/InspectorClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/InspectorFrontendClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/LinkHighlight.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PrerendererClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/android/WebInputEventFactory.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/linux/WebFontRendering.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/linux/WebFontRenderStyle.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/LocalFileSystemChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/MediaSourcePrivateImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/NotificationPresenterImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/painting/ContinuousPainter.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/painting/PaintAggregator.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PageOverlay.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PageOverlayList.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PageWidgetDelegate.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PopupContainer.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PopupMenuChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PopupListBox.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ScrollbarGroup.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/SharedWorkerRepository.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/SourceBufferPrivateImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/SpeechInputClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/SpeechRecognitionClientProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/StorageAreaProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/StorageQuotaChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/StorageNamespaceProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/TextFieldDecoratorImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/UserMediaClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ValidationMessageClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ViewportAnchor.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebTextCheckingCompletionImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebTextCheckingResult.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebAccessibilityObject.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebArrayBuffer.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebArrayBufferView.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebBindings.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebBlob.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebBlobData.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebCache.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebCachedURLRequest.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebColorName.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebCrossOriginPreflightResultCache.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMActivityLogger.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMCustomEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMEventListener.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMEventListenerPrivate.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMMessageEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMMouseEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMMutationEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMProgressEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMResourceProgressEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDatabase.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDataSourceImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDevToolsAgentImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDevToolsFrontendImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDeviceOrientation.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDeviceOrientationClientMock.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDeviceOrientationController.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDocument.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDocumentType.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDragData.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebEntities.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFileChooserCompletionImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFileSystemCallbacksImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFontCache.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFontDescription.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFontImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFormControlElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFormElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFrameImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationController.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationClientMock.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationError.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationPermissionRequest.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationPermissionRequestManager.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationPosition.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGlyphCache.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebHistoryItem.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebHitTestResult.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIconLoadingCompletionImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBCallbacksImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBDatabaseCallbacksImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBDatabaseError.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBKey.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBKeyPath.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBKeyRange.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBMetadata.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebImageCache.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebImageDecoder.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebImageSkia.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebInputElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebInputEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebInputEventConversion.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebKit.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebLabelElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebMediaPlayerClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebMediaSourceImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebMediaStreamRegistry.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebNetworkStateNotifier.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebNode.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebNodeCollection.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebNodeList.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebNotification.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebOptionElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPagePopupImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPageSerializer.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPageSerializerImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPasswordFormData.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPasswordFormUtils.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPerformance.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPluginContainerImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPluginDocument.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPluginLoadObserver.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPluginScrollbarImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPopupMenuImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebRange.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebRuntimeFeatures.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebScopedMicrotaskSuppression.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebScopedUserGesture.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebScriptController.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebScrollbarThemePainter.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSearchableFormData.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSecurityOrigin.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSecurityPolicy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSelectElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSerializedScriptValue.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSettingsImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSharedWorkerImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSocket.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSocketImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSpeechGrammar.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSpeechInputResult.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSpeechRecognitionHandle.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSpeechRecognitionResult.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebStorageEventDispatcherImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebStorageQuotaCallbacksImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSurroundingText.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebTextInputInfo.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebTextRun.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebURLLoadTiming.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebTextFieldDecoratorClient.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebUserGestureIndicator.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebUserGestureToken.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebUserMediaRequest.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebViewBenchmarkSupportImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebViewImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebWorkerBase.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebWorkerClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebWorkerInfo.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebWorkerRunLoop.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WorkerAllowMainThreadBridgeBase.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WorkerAsyncFileSystemChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WorkerAsyncFileWriterChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WorkerFileSystemCallbacksBridge.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WorkerFileWriterCallbacksBridge.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WorkerStorageQuotaCallbacksBridge.cpp


# Flags passed to both C and C++ files.
MY_CFLAGS := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	 \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-EL \
	-mhard-float \
	-mips32r2 \
	-Wa,-mips32r2 \
	--sysroot=/automerger/android-src/external/chromium_org/mipsel-sysroot/sysroot \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fstack-protector \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	-U_FORTIFY_SOURCE \
	-Wno-extra \
	-Wno-ignored-qualifiers \
	-Wno-type-limits \
	-Wno-address \
	-Wno-format-security \
	-Wno-return-type \
	-Wno-sequence-point \
	-Os \
	-g \
	-fomit-frame-pointer \
	-fdata-sections \
	-ffunction-sections

MY_CFLAGS_C :=

MY_DEFS := \
	'-DANGLE_DX11' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_GPU=1' \
	'-DUSE_OPENSSL=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DWEBKIT_IMPLEMENTATION=1' \
	'-DINSIDE_WEBKIT' \
	'-DENABLE_CANVAS_USES_MAILBOX=1' \
	'-DENABLE_CSS3_TEXT=0' \
	'-DENABLE_CSS_EXCLUSIONS=1' \
	'-DENABLE_CSS_REGIONS=1' \
	'-DENABLE_CUSTOM_SCHEME_HANDLER=0' \
	'-DENABLE_ENCRYPTED_MEDIA_V2=1' \
	'-DENABLE_GRAPHICS_CONTEXT_ANNOTATIONS=0' \
	'-DENABLE_SVG_FONTS=1' \
	'-DENABLE_TOUCH_ICON_LOADING=1' \
	'-DENABLE_XHR_TIMEOUT=0' \
	'-DENABLE_GDI_FONTS_ON_WINDOWS=1' \
	'-DWTF_USE_CONCATENATED_IMPULSE_RESPONSES=1' \
	'-DENABLE_CALENDAR_PICKER=0' \
	'-DENABLE_FAST_MOBILE_SCROLLING=1' \
	'-DENABLE_INPUT_SPEECH=0' \
	'-DENABLE_LEGACY_NOTIFICATIONS=0' \
	'-DENABLE_MEDIA_CAPTURE=1' \
	'-DENABLE_NOTIFICATIONS=0' \
	'-DENABLE_ORIENTATION_EVENTS=1' \
	'-DENABLE_PRINTING=0' \
	'-DENABLE_NAVIGATOR_CONTENT_UTILS=0' \
	'-DWTF_USE_NATIVE_FULLSCREEN_VIDEO=1' \
	'-DENABLE_8BIT_TEXTRUN=1' \
	'-DENABLE_OPENTYPE_VERTICAL=1' \
	'-DWTF_USE_HARFBUZZ=1' \
	'-DENABLE_PARTITION_ALLOC=1' \
	'-DU_USING_ICU_NAMESPACE=0' \
	'-DSK_BUILD_NO_IMAGE_ENCODE' \
	'-DSK_DEFERRED_CANVAS_USES_GPIPE=1' \
	'-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' \
	'-DGR_AGGRESSIVE_SHADER_OPTS=1' \
	'-DSK_ENABLE_INST_COUNT=0' \
	'-DSK_USE_POSIX_THREADS' \
	'-DSK_BUILD_FOR_ANDROID' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_BUILD_ID=""' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

LOCAL_CFLAGS := $(MY_CFLAGS_C) $(MY_CFLAGS) $(MY_DEFS)

# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebKit/chromium/public \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebKit/chromium/src \
	$(LOCAL_PATH)/third_party/angle_dx11/include \
	$(LOCAL_PATH)/third_party/skia/include/utils \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebKit/chromium/public/android \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebKit/chromium/public/linux \
	$(gyp_shared_intermediate_dir)/shim_headers/icui18n/target \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target \
	$(gyp_shared_intermediate_dir)/shim_headers/ashmem/target \
	$(LOCAL_PATH)/third_party/khronos \
	$(LOCAL_PATH)/gpu \
	$(LOCAL_PATH) \
	$(LOCAL_PATH)/third_party/WebKit \
	$(LOCAL_PATH)/third_party/WebKit/Source \
	$(gyp_shared_intermediate_dir)/webkit \
	$(gyp_shared_intermediate_dir)/webkit/bindings \
	$(PWD)/external/icu4c/common \
	$(PWD)/external/icu4c/i18n \
	$(LOCAL_PATH)/third_party/qcms/src \
	$(LOCAL_PATH)/skia/config \
	$(LOCAL_PATH)/third_party/skia/src/core \
	$(LOCAL_PATH)/third_party/skia/include/config \
	$(LOCAL_PATH)/third_party/skia/include/core \
	$(LOCAL_PATH)/third_party/skia/include/effects \
	$(LOCAL_PATH)/third_party/skia/include/pdf \
	$(LOCAL_PATH)/third_party/skia/include/gpu \
	$(LOCAL_PATH)/third_party/skia/include/gpu/gl \
	$(LOCAL_PATH)/third_party/skia/include/pathops \
	$(LOCAL_PATH)/third_party/skia/include/pipe \
	$(LOCAL_PATH)/third_party/skia/include/ports \
	$(LOCAL_PATH)/skia/ext \
	$(LOCAL_PATH)/third_party/npapi \
	$(LOCAL_PATH)/third_party/npapi/bindings \
	$(LOCAL_PATH)/v8/include \
	$(PWD)/frameworks/wilhelm/include \
	$(PWD)/bionic \
	$(PWD)/external/stlport/stlport

LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES)

# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS := \
	-Wno-c++0x-compat \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-Wno-uninitialized \
	-Wno-error=c++0x-compat \
	-Wno-non-virtual-dtor \
	-Wno-sign-promo \
	-Wno-non-virtual-dtor

### Rules for final target.

LOCAL_LDFLAGS := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-Wl,-z,noexecstack \
	-fPIC \
	-EL \
	-Wl,--no-keep-memory \
	--sysroot=/automerger/android-src/external/chromium_org/mipsel-sysroot/sysroot \
	 \
	-nostdlib \
	-Wl,--no-undefined \
	-Wl,--exclude-libs=ALL \
	-Wl,--gc-sections \
	-Wl,-O1 \
	-Wl,--as-needed


LOCAL_STATIC_LIBRARIES := \
	third_party_WebKit_Source_core_webcore_derived_gyp \
	skia_skia_gyp

# Enable grouping to fix circular references
LOCAL_GROUP_STATIC_LIBRARIES := true

LOCAL_SHARED_LIBRARIES := \
	libstlport \
	libdl

# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: third_party_WebKit_Source_WebKit_chromium_webkit_gyp

# Alias gyp target name.
.PHONY: webkit
webkit: third_party_WebKit_Source_WebKit_chromium_webkit_gyp

include $(BUILD_STATIC_LIBRARY)
