# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE := third_party_WebKit_Source_WebKit_chromium_webkit_gyp
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_TAGS := optional
gyp_intermediate_dir := $(call local-intermediates-dir)
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared)

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES := \
	$(call intermediates-dir-for,GYP,third_party_WebKit_Source_WebCore_WebCore_gyp_webcore_gyp)/webcore.stamp \
	$(call intermediates-dir-for,STATIC_LIBRARIES,third_party_WebKit_Source_WebCore_WebCore_gyp_webcore_bindings_gyp)/third_party_WebKit_Source_WebCore_WebCore_gyp_webcore_bindings_gyp.a \
	$(call intermediates-dir-for,STATIC_LIBRARIES,skia_skia_gyp)/skia_skia_gyp.a \
	$(call intermediates-dir-for,GYP,third_party_icu_icuuc_gyp)/icuuc.stamp \
	$(call intermediates-dir-for,GYP,third_party_npapi_npapi_gyp)/npapi.stamp \
	$(call intermediates-dir-for,GYP,v8_tools_gyp_v8_gyp)/v8.stamp

GYP_GENERATED_OUTPUTS :=

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

LOCAL_GENERATED_SOURCES :=

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	third_party/WebKit/Source/WebCore/platform/chromium/support/Extensions3DChromium.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/GraphicsContext3DChromium.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/GraphicsContext3DPrivate.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/PlatformGestureCurveFactory.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebAudioBus.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebData.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebHTTPBody.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebHTTPLoadInfo.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebMediaConstraints.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebMediaStreamComponent.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebMediaStreamDescriptor.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebMediaStreamSource.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebMediaStreamSourcesRequest.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebPrerender.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebRTCConfiguration.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebRTCDataChannel.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebRTCICECandidate.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebRTCSessionDescription.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebRTCSessionDescriptionRequest.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebRTCStatsRequest.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebRTCStatsResponse.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebRTCVoidRequest.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebScrollbarThemeGeometryNative.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebScrollbarImpl.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebSharedGraphicsContext3D.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebThreadSafeData.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebTransformOperations.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebTransformationMatrix.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebURL.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebURLError.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebURLRequest.cpp \
	third_party/WebKit/Source/WebCore/platform/chromium/support/WebURLResponse.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ApplicationCacheHost.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/AssertMatchingEnums.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/AssociatedURLLoader.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/AsyncFileSystemChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/AsyncFileWriterChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/AudioDestinationChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/AutofillPopupMenuClient.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/BackForwardListChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/BatteryClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/BlobRegistryProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DateTimeChooserImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ChromeClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ColorChooserUIController.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/CompositionUnderlineVectorBuilder.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ContextFeaturesClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ContextMenuClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DatabaseObserver.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DeliveredIntentClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DeviceOrientationClientProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DOMUtilitiesPrivate.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DragClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/DragScrollTimer.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/EditorClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/EventListenerWrapper.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ExternalPopupMenu.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/FindInPageCoordinates.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/FrameLoaderClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/GeolocationClientProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebHelperPluginImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBCallbacksProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBCursorBackendProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBDatabaseCallbacksProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBDatabaseBackendProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBFactoryBackendProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBIndexBackendProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBObjectStoreBackendProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBTransactionBackendProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/IDBTransactionCallbacksProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/InspectorClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/InspectorFrontendClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/LinkHighlight.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/NonCompositedContentHost.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PrerendererClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/android/WebInputEventFactory.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/linux/WebFontRendering.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/linux/WebFontRenderStyle.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/LocalFileSystemChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/LocalizedStrings.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/MediaPlayerPrivateChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/NotificationPresenterImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/painting/PaintAggregator.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PageOverlay.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PageOverlayList.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PageWidgetDelegate.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PlatformMessagePortChannel.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/PlatformSupport.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ScrollbarGroup.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/SharedWorkerRepository.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/SocketStreamHandle.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/SpeechInputClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/SpeechRecognitionClientProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/StorageAreaProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/StorageInfoChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/StorageNamespaceProxy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/TextFieldDecoratorImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/UserMediaClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/ValidationMessageClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebTextCheckingCompletionImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebTextCheckingResult.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebAccessibilityObject.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebAnimationControllerImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebArrayBuffer.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebArrayBufferView.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebBindings.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebBlob.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebBlobData.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebCache.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebColorName.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebCommon.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebCompositorInputHandlerImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebCrossOriginPreflightResultCache.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebCursorInfo.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMCustomEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMEventListener.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMEventListenerPrivate.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMMessageEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMMouseEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMMutationEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDOMStringList.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDatabase.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDataSourceImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDevToolsAgentImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDevToolsFrontendImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDeviceOrientation.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDeviceOrientationClientMock.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDeviceOrientationController.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDocument.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDocumentType.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebDragData.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebEntities.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFileChooserCompletionImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFileSystemCallbacksImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFontCache.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFontDescription.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFontImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFormControlElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFormElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebFrameImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationController.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationClientMock.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationError.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationPermissionRequest.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationPermissionRequestManager.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGeolocationPosition.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGlyphCache.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebGraphicsContext3D.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebHistoryItem.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebHitTestResult.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIconLoadingCompletionImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBCallbacksImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBCursorImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBDatabaseCallbacksImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBDatabaseError.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBDatabaseImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBFactoryImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBIndexImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBKey.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBKeyPath.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBKeyRange.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBMetadata.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBObjectStoreImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBTransactionImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIDBTransactionCallbacksImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebImageDecoder.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebImageSkia.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebInputElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebInputEvent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebInputEventConversion.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIntent.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIntentRequest.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebIntentServiceInfo.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebKit.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebLabelElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebMediaPlayerClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebMediaStreamRegistry.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebNetworkStateNotifier.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebNode.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebNodeCollection.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebNodeList.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebNotification.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebOptionElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPagePopupImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPageSerializer.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPageSerializerImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPasswordFormData.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPasswordFormUtils.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPerformance.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPluginContainerImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPluginDocument.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPluginListBuilderImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPluginLoadObserver.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPluginScrollbarImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebPopupMenuImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebRange.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebRegularExpression.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebRuntimeFeatures.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebScopedMicrotaskSuppression.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebScopedUserGesture.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebScriptController.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebScrollbarThemeClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebScrollbarThemePainter.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSearchableFormData.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSecurityOrigin.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSecurityPolicy.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSelectElement.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSerializedScriptValue.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSettingsImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSharedWorkerImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSocket.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSocketImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSpeechGrammar.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSpeechInputResult.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSpeechRecognitionHandle.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSpeechRecognitionResult.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebStorageEventDispatcherImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebStorageQuotaCallbacksImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebSurroundingText.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebTextInputInfo.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebTextRun.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebURLLoadTiming.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebTextFieldDecoratorClient.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebUserMediaRequest.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebViewBenchmarkSupportImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebViewImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebWorkerBase.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebWorkerClientImpl.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebWorkerInfo.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WebWorkerRunLoop.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WorkerAsyncFileSystemChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WorkerAsyncFileWriterChromium.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WorkerFileSystemCallbacksBridge.cpp \
	third_party/WebKit/Source/WebKit/chromium/src/WorkerFileWriterCallbacksBridge.cpp


# Flags passed to both C and C++ files.
MY_CFLAGS := \
	-Werror \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-mthumb \
	-march=armv7-a \
	-mtune=cortex-a8 \
	-mfloat-abi=softfp \
	-mfpu=vfpv3-d16 \
	-fno-tree-sra \
	-fuse-ld=gold \
	-Wno-psabi \
	-mthumb-interwork \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fstack-protector \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	-Wno-error=extra \
	-Wno-error=ignored-qualifiers \
	-Wno-error=type-limits \
	-Wno-error=non-virtual-dtor \
	-Wno-error=sign-promo \
	-Wno-error=address \
	-Wno-error=format-security \
	-Wno-error=non-virtual-dtor \
	-Wno-error=return-type \
	-Wno-error=sequence-point \
	-Os \
	-g \
	-fomit-frame-pointer \
	-fdata-sections \
	-ffunction-sections

MY_CFLAGS_C :=

MY_DEFS := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_GPU=1' \
	'-DUSE_OPENSSL=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DWEBKIT_IMPLEMENTATION=1' \
	'-DENABLE_3D_PLUGIN=1' \
	'-DENABLE_BATTERY_STATUS=0' \
	'-DENABLE_BLOB=1' \
	'-DENABLE_BLOB_SLICE=1' \
	'-DENABLE_CHANNEL_MESSAGING=1' \
	'-DENABLE_CSP_NEXT=1' \
	'-DENABLE_CSS3_CONDITIONAL_RULES=0' \
	'-DENABLE_CSS3_TEXT=0' \
	'-DENABLE_CSS_BOX_DECORATION_BREAK=1' \
	'-DENABLE_CSS_COMPOSITING=0' \
	'-DENABLE_CSS_DEVICE_ADAPTATION=0' \
	'-DENABLE_CSS_EXCLUSIONS=1' \
	'-DENABLE_CSS_FILTERS=1' \
	'-DENABLE_CSS_HIERARCHIES=0' \
	'-DENABLE_CSS_IMAGE_SET=1' \
	'-DENABLE_CSS_IMAGE_RESOLUTION=0' \
	'-DENABLE_CSS_REGIONS=1' \
	'-DENABLE_CSS_SHADERS=1' \
	'-DENABLE_CSS_VARIABLES=1' \
	'-DENABLE_CSS_STICKY_POSITION=1' \
	'-DENABLE_CUSTOM_SCHEME_HANDLER=0' \
	'-DENABLE_DASHBOARD_SUPPORT=0' \
	'-DENABLE_DATA_TRANSFER_ITEMS=1' \
	'-DENABLE_DETAILS_ELEMENT=1' \
	'-DENABLE_DEVICE_ORIENTATION=1' \
	'-DENABLE_DIALOG_ELEMENT=1' \
	'-DENABLE_DIRECTORY_UPLOAD=1' \
	'-DENABLE_DOWNLOAD_ATTRIBUTE=1' \
	'-DENABLE_DRAGGABLE_REGION=1' \
	'-DENABLE_ENCRYPTED_MEDIA=1' \
	'-DENABLE_FILE_SYSTEM=1' \
	'-DENABLE_FILTERS=1' \
	'-DENABLE_FULLSCREEN_API=1' \
	'-DENABLE_GAMEPAD=1' \
	'-DENABLE_GEOLOCATION=1' \
	'-DENABLE_GESTURE_EVENTS=1' \
	'-DENABLE_ICONDATABASE=0' \
	'-DENABLE_IFRAME_SEAMLESS=1' \
	'-DENABLE_INDEXED_DATABASE=1' \
	'-DENABLE_INPUT_TYPE_DATE=1' \
	'-DENABLE_INPUT_TYPE_DATETIME=1' \
	'-DENABLE_INPUT_TYPE_DATETIMELOCAL=1' \
	'-DENABLE_INPUT_TYPE_MONTH=1' \
	'-DENABLE_INPUT_TYPE_TIME=1' \
	'-DENABLE_JAVASCRIPT_DEBUGGER=1' \
	'-DENABLE_JAVASCRIPT_I18N_API=1' \
	'-DENABLE_LEGACY_CSS_VENDOR_PREFIXES=0' \
	'-DENABLE_LEGACY_VIEWPORT_ADAPTION=1' \
	'-DENABLE_LEGACY_VENDOR_PREFIXES=0' \
	'-DENABLE_LEGACY_WEB_AUDIO=1' \
	'-DENABLE_LINK_PREFETCH=1' \
	'-DENABLE_LINK_PRERENDER=1' \
	'-DENABLE_MATHML=1' \
	'-DENABLE_MEDIA_SOURCE=1' \
	'-DENABLE_MEDIA_STATISTICS=1' \
	'-DENABLE_METER_ELEMENT=1' \
	'-DENABLE_MHTML=1' \
	'-DENABLE_MICRODATA=0' \
	'-DENABLE_MUTATION_OBSERVERS=1' \
	'-DENABLE_NAVIGATOR_CONTENT_UTILS=1' \
	'-DENABLE_PAGE_VISIBILITY_API=1' \
	'-DENABLE_POINTER_LOCK=1' \
	'-DENABLE_PROGRESS_ELEMENT=1' \
	'-DENABLE_QUOTA=1' \
	'-DENABLE_RESOLUTION_MEDIA_QUERY=0' \
	'-DENABLE_REQUEST_ANIMATION_FRAME=1' \
	'-DENABLE_REQUEST_AUTOCOMPLETE=1' \
	'-DENABLE_RUBY=1' \
	'-DENABLE_SANDBOX=1' \
	'-DENABLE_SCRIPTED_SPEECH=1' \
	'-DENABLE_SHADOW_DOM=1' \
	'-DENABLE_SMOOTH_SCROLLING=1' \
	'-DENABLE_SQL_DATABASE=1' \
	'-DENABLE_STYLE_SCOPED=1' \
	'-DENABLE_SVG=1' \
	'-DENABLE_SVG_FONTS=1' \
	'-DENABLE_TEXT_AUTOSIZING=1' \
	'-DENABLE_TOUCH_ADJUSTMENT=1' \
	'-DENABLE_TOUCH_EVENTS=1' \
	'-DENABLE_TOUCH_ICON_LOADING=1' \
	'-DENABLE_TOUCH_SLIDER=1' \
	'-DENABLE_V8_SCRIPT_DEBUG_SERVER=1' \
	'-DENABLE_VIDEO=1' \
	'-DENABLE_VIDEO_TRACK=1' \
	'-DENABLE_VIEWPORT=1' \
	'-DENABLE_WEBGL=1' \
	'-DENABLE_WEB_INTENTS=1' \
	'-DENABLE_WEB_SOCKETS=1' \
	'-DENABLE_WEB_TIMING=1' \
	'-DENABLE_WORKERS=1' \
	'-DENABLE_XHR_RESPONSE_BLOB=1' \
	'-DENABLE_XHR_TIMEOUT=0' \
	'-DENABLE_XSLT=1' \
	'-DWTF_USE_LEVELDB=1' \
	'-DWTF_USE_BUILTIN_UTF8_CODEC=1' \
	'-DWTF_USE_OPENTYPE_SANITIZER=1' \
	'-DWTF_USE_RTL_SCROLLBAR=1' \
	'-DWTF_USE_SKIA_TEXT=1' \
	'-DWTF_USE_WEBP=1' \
	'-DWTF_USE_WEBKIT_IMAGE_DECODERS=1' \
	'-DENABLE_ACCELERATED_OVERFLOW_SCROLLING=1' \
	'-DENABLE_CALENDAR_PICKER=0' \
	'-DENABLE_DATALIST_ELEMENT=0' \
	'-DENABLE_FAST_MOBILE_SCROLLING=1' \
	'-DENABLE_INPUT_SPEECH=0' \
	'-DENABLE_INPUT_TYPE_COLOR=0' \
	'-DENABLE_INPUT_TYPE_WEEK=0' \
	'-DENABLE_LEGACY_NOTIFICATIONS=0' \
	'-DENABLE_MEDIA_CAPTURE=1' \
	'-DENABLE_MEDIA_STREAM=0' \
	'-DENABLE_NOTIFICATIONS=0' \
	'-DENABLE_ORIENTATION_EVENTS=1' \
	'-DENABLE_PAGE_POPUP=0' \
	'-DENABLE_PRINTING=0' \
	'-DENABLE_REGISTER_PROTOCOL_HANDLER=0' \
	'-DENABLE_SHARED_WORKERS=1' \
	'-DENABLE_WEB_AUDIO=0' \
	'-DWTF_USE_NATIVE_FULLSCREEN_VIDEO=1' \
	'-DENABLE_3D_RENDERING=1' \
	'-DENABLE_ACCELERATED_2D_CANVAS=1' \
	'-DWTF_USE_ACCELERATED_COMPOSITING=1' \
	'-DENABLE_OPENTYPE_VERTICAL=1' \
	'-DBUILDING_CHROMIUM__=1' \
	'-DUSE_SYSTEM_MALLOC=1' \
	'-DWTF_USE_PTHREADS=1' \
	'-DU_USING_ICU_NAMESPACE=0' \
	'-DUSE_SYSTEM_ICU' \
	'-DSK_BUILD_NO_IMAGE_ENCODE' \
	'-DSK_DEFERRED_CANVAS_USES_GPIPE=1' \
	'-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' \
	'-DGR_AGGRESSIVE_SHADER_OPTS=1' \
	'-DSK_USE_POSIX_THREADS' \
	'-DSK_BUILD_FOR_ANDROID_NDK' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_SYMBOLS_ID=""' \
	'-DANDROID_UPSTREAM_BRINGUP=1' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

LOCAL_CFLAGS := $(MY_CFLAGS_C) $(MY_CFLAGS) $(MY_DEFS)

# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebKit/chromium/public \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebKit/chromium/src \
	$(LOCAL_PATH)/third_party/angle/include \
	$(LOCAL_PATH)/third_party/skia/include/utils \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebKit/chromium/public/android \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebKit/chromium/public/linux \
	$(LOCAL_PATH)/third_party/khronos \
	$(LOCAL_PATH) \
	$(LOCAL_PATH)/third_party/WebKit/Source/Platform/chromium \
	$(gyp_shared_intermediate_dir)/webcore_headers \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore \
	$(LOCAL_PATH)/third_party/WebKit/Source \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/battery \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/filesystem \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/filesystem/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/gamepad \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/geolocation \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/intents \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/indexeddb \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/mediasource \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/mediastream \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/navigatorcontentutils \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/notifications \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/quota \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/speech \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/webaudio \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/webdatabase \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/webdatabase/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/websockets \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/accessibility \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/accessibility/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bindings \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bindings/generic \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bindings/v8 \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bindings/v8/custom \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bridge \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bridge/jni \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bridge/jni/v8 \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/css \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/dom \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/dom/default \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/editing \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/fileapi \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/history \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/html \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/html/canvas \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/html/parser \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/html/shadow \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/html/track \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/inspector \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/appcache \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/archive \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/archive/cf \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/archive/mhtml \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/cache \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/icon \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/mathml \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/page \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/page/animation \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/page/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/page/scrolling \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/page/scrolling/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/animation \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/audio \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/audio/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/chromium/support \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/cc \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/filters \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/filters/arm \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/filters/skia \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/gpu \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/opentype \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/skia \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/transforms \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/bmp \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/gif \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/ico \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/jpeg \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/png \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/skia \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/webp \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-encoders/skia \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/leveldb \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/mediastream \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/mediastream/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/mock \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/network \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/network/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/sql \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/text \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/text/transcoder \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/plugins \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/plugins/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/rendering \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/rendering/mathml \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/rendering/style \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/rendering/svg \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/storage \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/storage/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/svg \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/svg/animation \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/svg/graphics \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/svg/graphics/filters \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/svg/properties \
	$(LOCAL_PATH)/third_party/WebKit/Source/ThirdParty/glu \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/workers \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/xml \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/xml/parser \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/harfbuzz \
	$(gyp_shared_intermediate_dir)/webkit \
	$(gyp_shared_intermediate_dir)/webkit/bindings \
	$(LOCAL_PATH)/third_party/WebKit/Source/WTF \
	$(LOCAL_PATH)/third_party/WebKit/Source/JavaScriptCore \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/icu4c/common \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/icu4c/i18n \
	$(LOCAL_PATH)/third_party/qcms/src \
	$(LOCAL_PATH)/skia/config \
	$(LOCAL_PATH)/third_party/skia/src/core \
	$(LOCAL_PATH)/third_party/skia/include/config \
	$(LOCAL_PATH)/third_party/skia/include/core \
	$(LOCAL_PATH)/third_party/skia/include/effects \
	$(LOCAL_PATH)/third_party/skia/include/pdf \
	$(LOCAL_PATH)/third_party/skia/include/gpu \
	$(LOCAL_PATH)/third_party/skia/include/gpu/gl \
	$(LOCAL_PATH)/third_party/skia/include/pipe \
	$(LOCAL_PATH)/third_party/skia/include/ports \
	$(LOCAL_PATH)/skia/ext \
	$(LOCAL_PATH)/third_party/harfbuzz/contrib \
	$(LOCAL_PATH)/third_party/harfbuzz/src \
	$(LOCAL_PATH)/third_party/npapi \
	$(LOCAL_PATH)/third_party/npapi/bindings \
	$(LOCAL_PATH)/v8/include \
	$(GYP_ABS_ANDROID_TOP_DIR)/frameworks/wilhelm/include \
	$(GYP_ABS_ANDROID_TOP_DIR)/bionic \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/stlport/stlport

LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES)

# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS := \
	-Wno-c++0x-compat \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-Wno-abi \
	-Wno-error=c++0x-compat

### Rules for final target.

LOCAL_LDFLAGS := \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-z,relro \
	-Wl,-z,now \
	-fuse-ld=gold \
	-nostdlib \
	-Wl,--no-undefined \
	-Wl,--exclude-libs=ALL \
	-Wl,--icf=safe \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections


LOCAL_STATIC_LIBRARIES := \
	third_party_WebKit_Source_WebCore_WebCore_gyp_webcore_bindings_gyp \
	skia_skia_gyp

# Enable grouping to fix circular references
LOCAL_GROUP_STATIC_LIBRARIES := true

LOCAL_SHARED_LIBRARIES := \
	libstlport \
	libdl

# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: third_party_WebKit_Source_WebKit_chromium_webkit_gyp

# Alias gyp target name.
.PHONY: webkit
webkit: third_party_WebKit_Source_WebKit_chromium_webkit_gyp

include $(BUILD_STATIC_LIBRARY)
