# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE := third_party_WebKit_Source_WebCore_WebCore_gyp_webcore_rendering_gyp
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_TAGS := optional
gyp_intermediate_dir := $(call local-intermediates-dir)
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared)

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES := \
	$(call intermediates-dir-for,GYP,third_party_WebKit_Source_WebCore_WebCore_gyp_webcore_prerequisites_gyp)/webcore_prerequisites.stamp \
	$(call intermediates-dir-for,STATIC_LIBRARIES,skia_skia_gyp)/skia_skia_gyp.a

GYP_GENERATED_OUTPUTS :=

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

LOCAL_GENERATED_SOURCES :=

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	third_party/WebKit/Source/WebCore/rendering/AutoTableLayout.cpp \
	third_party/WebKit/Source/WebCore/rendering/BidiRun.cpp \
	third_party/WebKit/Source/WebCore/rendering/CounterNode.cpp \
	third_party/WebKit/Source/WebCore/rendering/EllipsisBox.cpp \
	third_party/WebKit/Source/WebCore/rendering/ExclusionInterval.cpp \
	third_party/WebKit/Source/WebCore/rendering/ExclusionPolygon.cpp \
	third_party/WebKit/Source/WebCore/rendering/ExclusionRectangle.cpp \
	third_party/WebKit/Source/WebCore/rendering/ExclusionShape.cpp \
	third_party/WebKit/Source/WebCore/rendering/ExclusionShapeInfo.cpp \
	third_party/WebKit/Source/WebCore/rendering/ExclusionShapeInsideInfo.cpp \
	third_party/WebKit/Source/WebCore/rendering/ExclusionShapeOutsideInfo.cpp \
	third_party/WebKit/Source/WebCore/rendering/FilterEffectRenderer.cpp \
	third_party/WebKit/Source/WebCore/rendering/FixedTableLayout.cpp \
	third_party/WebKit/Source/WebCore/rendering/FlowThreadController.cpp \
	third_party/WebKit/Source/WebCore/rendering/TextAutosizer.cpp \
	third_party/WebKit/Source/WebCore/rendering/HitTestingTransformState.cpp \
	third_party/WebKit/Source/WebCore/rendering/HitTestLocation.cpp \
	third_party/WebKit/Source/WebCore/rendering/HitTestResult.cpp \
	third_party/WebKit/Source/WebCore/rendering/InlineBox.cpp \
	third_party/WebKit/Source/WebCore/rendering/InlineFlowBox.cpp \
	third_party/WebKit/Source/WebCore/rendering/InlineTextBox.cpp \
	third_party/WebKit/Source/WebCore/rendering/LayoutState.cpp \
	third_party/WebKit/Source/WebCore/rendering/LayoutRepainter.cpp \
	third_party/WebKit/Source/WebCore/rendering/PointerEventsHitRules.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderApplet.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderArena.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderBR.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderBlock.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderBlockLineLayout.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderBox.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderBoxModelObject.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderButton.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderCombineText.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderCounter.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderDeprecatedFlexibleBox.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderDetailsMarker.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderDialog.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderEmbeddedObject.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderFieldset.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderFileUploadControl.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderFlexibleBox.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderFlowThread.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderFrame.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderFrameBase.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderFrameSet.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderFullScreen.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderGrid.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderGeometryMap.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderHTMLCanvas.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderIFrame.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderImage.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderImageResource.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderImageResourceStyleImage.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderInline.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderInputSpeech.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderLayer.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderLayerBacking.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderLayerCompositor.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderLayerFilterInfo.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderLayerModelObject.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderLineBoxList.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderListBox.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderListItem.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderListMarker.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderMarquee.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderMedia.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderMediaControlElements.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderMediaControls.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderMediaControlsChromium.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderMenuList.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderMeter.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderMultiColumnBlock.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderMultiColumnFlowThread.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderMultiColumnSet.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderNamedFlowThread.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderObject.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderObjectChildList.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderPart.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderProgress.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderQuote.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderRegion.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderRegionSet.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderReplaced.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderReplica.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderRuby.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderRubyBase.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderRubyRun.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderRubyText.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderScrollbar.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderScrollbarPart.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderScrollbarTheme.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderSearchField.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderSlider.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderSnapshottedPlugIn.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTable.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTableCaption.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTableCell.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTableCol.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTableRow.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTableSection.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderText.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTextControl.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTextControlMultiLine.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTextControlSingleLine.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTextFragment.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTextTrackCue.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTheme.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderThemeChromiumAndroid.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderThemeChromiumCommon.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderThemeChromiumDefault.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderThemeChromiumFontProvider.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderThemeChromiumFontProviderLinux.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderThemeChromiumSkia.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderTreeAsText.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderVideo.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderView.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderWidget.cpp \
	third_party/WebKit/Source/WebCore/rendering/RenderWordBreak.cpp \
	third_party/WebKit/Source/WebCore/rendering/RootInlineBox.cpp \
	third_party/WebKit/Source/WebCore/rendering/ScrollBehavior.cpp \
	third_party/WebKit/Source/WebCore/rendering/break_lines.cpp \
	third_party/WebKit/Source/WebCore/rendering/mathml/RenderMathMLBlock.cpp \
	third_party/WebKit/Source/WebCore/rendering/mathml/RenderMathMLFenced.cpp \
	third_party/WebKit/Source/WebCore/rendering/mathml/RenderMathMLFraction.cpp \
	third_party/WebKit/Source/WebCore/rendering/mathml/RenderMathMLMath.cpp \
	third_party/WebKit/Source/WebCore/rendering/mathml/RenderMathMLOperator.cpp \
	third_party/WebKit/Source/WebCore/rendering/mathml/RenderMathMLRoot.cpp \
	third_party/WebKit/Source/WebCore/rendering/mathml/RenderMathMLRow.cpp \
	third_party/WebKit/Source/WebCore/rendering/mathml/RenderMathMLSquareRoot.cpp \
	third_party/WebKit/Source/WebCore/rendering/mathml/RenderMathMLSubSup.cpp \
	third_party/WebKit/Source/WebCore/rendering/mathml/RenderMathMLUnderOver.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/BasicShapes.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/ContentData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/CounterDirectives.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/FillLayer.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/KeyframeList.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/NinePieceImage.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/QuotesData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/RenderStyle.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/ShadowData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleBackgroundData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleBoxData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleCachedImage.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleCachedImageSet.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleCachedShader.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleCustomFilterProgramCache.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleCustomFilterProgram.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleDeprecatedFlexibleBoxData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleFilterData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleFlexibleBoxData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleGeneratedImage.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleGridData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleGridItemData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleInheritedData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleMarqueeData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleMultiColData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleRareInheritedData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleRareNonInheritedData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleSurroundData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleTransformData.cpp \
	third_party/WebKit/Source/WebCore/rendering/style/StyleVisualData.cpp


# Flags passed to both C and C++ files.
MY_CFLAGS := \
	--param=ssp-buffer-size=4 \
	-Werror \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-uninitialized \
	-m32 \
	-mmmx \
	-march=pentium4 \
	-msse2 \
	-mfpmath=sse \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	-U_FORTIFY_SOURCE \
	-Wno-extra \
	-Wno-ignored-qualifiers \
	-Wno-type-limits \
	-fno-stack-protector \
	-Os \
	-g \
	-fomit-frame-pointer \
	-fdata-sections \
	-ffunction-sections

MY_CFLAGS_C :=

MY_DEFS := \
	'-DUSE_SKIA' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_GPU=1' \
	'-DUSE_OPENSSL=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DWEBCORE_NAVIGATOR_VENDOR="Google Inc."' \
	'-DWEBKIT_IMPLEMENTATION=1' \
	'-DENABLE_3D_PLUGIN=1' \
	'-DENABLE_BATTERY_STATUS=0' \
	'-DENABLE_BLOB=1' \
	'-DENABLE_BLOB_SLICE=1' \
	'-DENABLE_CANVAS_PATH=1' \
	'-DENABLE_CANVAS_PROXY=1' \
	'-DENABLE_CHANNEL_MESSAGING=1' \
	'-DENABLE_CSP_NEXT=1' \
	'-DENABLE_CSS3_CONDITIONAL_RULES=0' \
	'-DENABLE_CSS3_TEXT=0' \
	'-DENABLE_CSS3_TEXT_LINE_BREAK=0' \
	'-DENABLE_CSS_BOX_DECORATION_BREAK=1' \
	'-DENABLE_CSS_COMPOSITING=0' \
	'-DENABLE_CSS_DEVICE_ADAPTATION=0' \
	'-DENABLE_CSS_EXCLUSIONS=1' \
	'-DENABLE_CSS_FILTERS=1' \
	'-DENABLE_CSS_IMAGE_SET=1' \
	'-DENABLE_CSS_IMAGE_RESOLUTION=0' \
	'-DENABLE_CSS_REGIONS=1' \
	'-DENABLE_CSS_SHADERS=1' \
	'-DENABLE_CSS_TRANSFORMS_ANIMATIONS_UNPREFIXED=0' \
	'-DENABLE_CSS_VARIABLES=1' \
	'-DENABLE_CSS_STICKY_POSITION=1' \
	'-DENABLE_CUSTOM_ELEMENTS=1' \
	'-DENABLE_CUSTOM_SCHEME_HANDLER=0' \
	'-DENABLE_DASHBOARD_SUPPORT=0' \
	'-DENABLE_DATA_TRANSFER_ITEMS=1' \
	'-DENABLE_DETAILS_ELEMENT=1' \
	'-DENABLE_DEVICE_ORIENTATION=1' \
	'-DENABLE_DIALOG_ELEMENT=1' \
	'-DENABLE_DIRECTORY_UPLOAD=1' \
	'-DENABLE_DOM4_EVENTS_CONSTRUCTOR=1' \
	'-DENABLE_DOWNLOAD_ATTRIBUTE=1' \
	'-DENABLE_DRAGGABLE_REGION=1' \
	'-DENABLE_ENCRYPTED_MEDIA=1' \
	'-DENABLE_FILE_SYSTEM=1' \
	'-DENABLE_FILTERS=1' \
	'-DENABLE_FONT_LOAD_EVENTS=1' \
	'-DENABLE_FULLSCREEN_API=1' \
	'-DENABLE_GAMEPAD=1' \
	'-DENABLE_GEOLOCATION=1' \
	'-DENABLE_GESTURE_EVENTS=1' \
	'-DENABLE_ICONDATABASE=0' \
	'-DENABLE_IFRAME_SEAMLESS=1' \
	'-DENABLE_INDEXED_DATABASE=1' \
	'-DENABLE_INPUT_TYPE_DATE=1' \
	'-DENABLE_INPUT_TYPE_DATETIMELOCAL=1' \
	'-DENABLE_INPUT_TYPE_MONTH=1' \
	'-DENABLE_INPUT_TYPE_TIME=1' \
	'-DENABLE_JAVASCRIPT_DEBUGGER=1' \
	'-DENABLE_JAVASCRIPT_I18N_API=1' \
	'-DENABLE_LEGACY_CSS_VENDOR_PREFIXES=0' \
	'-DENABLE_LEGACY_VIEWPORT_ADAPTION=1' \
	'-DENABLE_LEGACY_VENDOR_PREFIXES=0' \
	'-DENABLE_LEGACY_WEB_AUDIO=1' \
	'-DENABLE_LINK_PREFETCH=1' \
	'-DENABLE_LINK_PRERENDER=1' \
	'-DENABLE_MATHML=0' \
	'-DENABLE_MEDIA_SOURCE=1' \
	'-DENABLE_MEDIA_STATISTICS=1' \
	'-DENABLE_MEDIA_STREAM=0' \
	'-DENABLE_METER_ELEMENT=1' \
	'-DENABLE_MHTML=1' \
	'-DENABLE_MICRODATA=0' \
	'-DENABLE_MOUSE_CURSOR_SCALE=1' \
	'-DENABLE_NOSNIFF=1' \
	'-DENABLE_PAGE_VISIBILITY_API=1' \
	'-DENABLE_PERFORMANCE_TIMELINE=1' \
	'-DENABLE_POINTER_LOCK=1' \
	'-DENABLE_PROGRESS_ELEMENT=1' \
	'-DENABLE_PROXIMITY_EVENTS=0' \
	'-DENABLE_QUOTA=1' \
	'-DENABLE_REQUEST_ANIMATION_FRAME=1' \
	'-DENABLE_REQUEST_AUTOCOMPLETE=1' \
	'-DENABLE_RESOLUTION_MEDIA_QUERY=0' \
	'-DENABLE_RESOURCE_TIMING=1' \
	'-DENABLE_RUBY=1' \
	'-DENABLE_SANDBOX=1' \
	'-DENABLE_SCRIPTED_SPEECH=1' \
	'-DENABLE_SHADOW_DOM=1' \
	'-DENABLE_SMOOTH_SCROLLING=1' \
	'-DENABLE_SPEECH_SYNTHESIS=0' \
	'-DENABLE_SQL_DATABASE=1' \
	'-DENABLE_STYLE_SCOPED=1' \
	'-DENABLE_SUBPIXEL_LAYOUT=1' \
	'-DENABLE_SVG=1' \
	'-DENABLE_SVG_FONTS=1' \
	'-DENABLE_TEMPLATE_ELEMENT=1' \
	'-DENABLE_TEXT_AUTOSIZING=1' \
	'-DENABLE_THREADED_HTML_PARSER=1' \
	'-DENABLE_TOUCH_ADJUSTMENT=1' \
	'-DENABLE_TOUCH_EVENTS=1' \
	'-DENABLE_TOUCH_EVENT_TRACKING=1' \
	'-DENABLE_TOUCH_ICON_LOADING=1' \
	'-DENABLE_TOUCH_SLIDER=1' \
	'-DENABLE_USER_TIMING=1' \
	'-DENABLE_V8_SCRIPT_DEBUG_SERVER=1' \
	'-DENABLE_VIDEO=1' \
	'-DENABLE_VIDEO_TRACK=1' \
	'-DENABLE_VIEWPORT=1' \
	'-DENABLE_VIEW_MODE_CSS_MEDIA=1' \
	'-DENABLE_WEBGL=1' \
	'-DENABLE_WEB_SOCKETS=1' \
	'-DENABLE_WEB_TIMING=1' \
	'-DENABLE_WORKERS=1' \
	'-DENABLE_XHR_TIMEOUT=0' \
	'-DENABLE_XSLT=1' \
	'-DWTF_USE_LEVELDB=1' \
	'-DWTF_USE_BUILTIN_UTF8_CODEC=1' \
	'-DWTF_USE_OPENTYPE_SANITIZER=1' \
	'-DWTF_USE_RTL_SCROLLBAR=1' \
	'-DWTF_USE_SKIA_TEXT=1' \
	'-DWTF_USE_WEBP=1' \
	'-DWTF_USE_WEBKIT_IMAGE_DECODERS=1' \
	'-DENABLE_CALENDAR_PICKER=0' \
	'-DENABLE_DATALIST_ELEMENT=0' \
	'-DENABLE_FAST_MOBILE_SCROLLING=1' \
	'-DENABLE_INPUT_SPEECH=0' \
	'-DENABLE_INPUT_TYPE_COLOR=0' \
	'-DENABLE_INPUT_TYPE_WEEK=0' \
	'-DENABLE_LEGACY_NOTIFICATIONS=0' \
	'-DENABLE_MEDIA_CAPTURE=1' \
	'-DENABLE_NOTIFICATIONS=0' \
	'-DENABLE_ORIENTATION_EVENTS=1' \
	'-DENABLE_PAGE_POPUP=0' \
	'-DENABLE_PRINTING=0' \
	'-DENABLE_NAVIGATOR_CONTENT_UTILS=0' \
	'-DENABLE_SHARED_WORKERS=1' \
	'-DENABLE_WEB_AUDIO=0' \
	'-DWTF_USE_NATIVE_FULLSCREEN_VIDEO=1' \
	'-DENABLE_8BIT_TEXTRUN=1' \
	'-DENABLE_BINDING_INTEGRITY=1' \
	'-DENABLE_3D_RENDERING=1' \
	'-DENABLE_ACCELERATED_2D_CANVAS=1' \
	'-DWTF_USE_ACCELERATED_COMPOSITING=1' \
	'-DENABLE_OPENTYPE_VERTICAL=1' \
	'-DWTF_USE_HARFBUZZ=1' \
	'-DBUILDING_CHROMIUM__=1' \
	'-DU_USING_ICU_NAMESPACE=0' \
	'-DSK_BUILD_NO_IMAGE_ENCODE' \
	'-DSK_DEFERRED_CANVAS_USES_GPIPE=1' \
	'-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' \
	'-DGR_AGGRESSIVE_SHADER_OPTS=1' \
	'-DSK_ENABLE_INST_COUNT=0' \
	'-DSK_USE_POSIX_THREADS' \
	'-DSK_BUILD_FOR_ANDROID_NDK' \
	'-DCHROME_PNG_WRITE_SUPPORT' \
	'-DPNG_USER_CONFIG' \
	'-DLIBXML_STATIC' \
	'-DLIBXSLT_STATIC' \
	'-DUSE_SYSTEM_LIBJPEG' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_BUILD_ID=""' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

LOCAL_CFLAGS := $(MY_CFLAGS_C) $(MY_CFLAGS) $(MY_DEFS)

# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES := \
	$(gyp_shared_intermediate_dir)/shim_headers/icuuc/target \
	$(gyp_shared_intermediate_dir)/shim_headers/icui18n/target \
	$(LOCAL_PATH)/third_party/khronos \
	$(LOCAL_PATH)/gpu \
	$(LOCAL_PATH) \
	$(LOCAL_PATH)/third_party/WebKit/Source/Platform/chromium \
	$(gyp_intermediate_dir) \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore \
	$(LOCAL_PATH)/third_party/WebKit/Source \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/battery \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/filesystem \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/filesystem/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/gamepad \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/geolocation \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/indexeddb \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/indexeddb/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/mediasource \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/mediastream \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/navigatorcontentutils \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/notifications \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/proximity \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/quota \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/speech \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/webaudio \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/webdatabase \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/webdatabase/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/Modules/websockets \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/accessibility \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/accessibility/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bindings \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bindings/generic \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bindings/v8 \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bindings/v8/custom \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bridge \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bridge/jni \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/bridge/jni/v8 \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/css \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/dom \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/dom/default \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/dom/default/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/editing \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/fileapi \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/history \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/html \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/html/canvas \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/html/parser \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/html/shadow \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/html/track \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/inspector \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/appcache \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/archive \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/archive/cf \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/archive/mhtml \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/cache \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/loader/icon \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/mathml \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/page \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/page/animation \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/page/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/page/scrolling \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/page/scrolling/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/animation \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/audio \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/audio/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/chromium/support \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/chromium/cc \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/cpu/arm \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/cpu/arm/filters \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/filters \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/filters/skia \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/gpu \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/opentype \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/skia \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/transforms \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/bmp \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/gif \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/ico \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/jpeg \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/png \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/skia \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-decoders/webp \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/image-encoders/skia \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/leveldb \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/mediastream \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/mediastream/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/mock \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/network \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/network/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/sql \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/text \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/text/transcoder \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/plugins \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/plugins/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/rendering \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/rendering/mathml \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/rendering/style \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/rendering/svg \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/storage \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/svg \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/svg/animation \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/svg/graphics \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/svg/graphics/filters \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/svg/properties \
	$(LOCAL_PATH)/third_party/WebKit/Source/ThirdParty/glu \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/workers \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/workers/chromium \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/xml \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/xml/parser \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/harfbuzz \
	$(LOCAL_PATH)/third_party/WebKit/Source/WebCore/platform/graphics/harfbuzz/ng \
	$(LOCAL_PATH)/third_party/angle/include/GLSLANG \
	$(gyp_shared_intermediate_dir)/webkit \
	$(gyp_shared_intermediate_dir)/webkit/bindings \
	$(LOCAL_PATH)/third_party/WebKit/Source/WTF \
	$(LOCAL_PATH)/third_party/WebKit/Source/JavaScriptCore \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/icu4c/common \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/icu4c/i18n \
	$(LOCAL_PATH)/skia/config \
	$(LOCAL_PATH)/third_party/skia/src/core \
	$(LOCAL_PATH)/third_party/skia/include/config \
	$(LOCAL_PATH)/third_party/skia/include/core \
	$(LOCAL_PATH)/third_party/skia/include/effects \
	$(LOCAL_PATH)/third_party/skia/include/pdf \
	$(LOCAL_PATH)/third_party/skia/include/gpu \
	$(LOCAL_PATH)/third_party/skia/include/gpu/gl \
	$(LOCAL_PATH)/third_party/skia/include/pipe \
	$(LOCAL_PATH)/third_party/skia/include/ports \
	$(LOCAL_PATH)/third_party/skia/include/utils \
	$(LOCAL_PATH)/skia/ext \
	$(LOCAL_PATH)/third_party/iccjpeg \
	$(LOCAL_PATH)/third_party/libwebp \
	$(LOCAL_PATH)/third_party/libpng \
	$(LOCAL_PATH)/third_party/libxml/linux/include \
	$(LOCAL_PATH)/third_party/libxml/src/include \
	$(LOCAL_PATH)/third_party/libxslt \
	$(LOCAL_PATH)/third_party/npapi \
	$(LOCAL_PATH)/third_party/npapi/bindings \
	$(LOCAL_PATH)/third_party/ots/include \
	$(LOCAL_PATH)/third_party/qcms/src \
	$(LOCAL_PATH)/third_party/sqlite \
	$(LOCAL_PATH)/third_party/zlib \
	$(LOCAL_PATH)/v8/include \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/jpeg \
	$(LOCAL_PATH)/third_party/leveldatabase/src/include \
	$(LOCAL_PATH)/third_party/leveldatabase/src \
	$(LOCAL_PATH)/third_party/leveldatabase \
	$(GYP_ABS_ANDROID_TOP_DIR)/frameworks/wilhelm/include \
	$(GYP_ABS_ANDROID_TOP_DIR)/bionic \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/stlport/stlport

LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES)

# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS := \
	-Wno-c++0x-compat \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-Wno-error=c++0x-compat \
	-Wno-non-virtual-dtor \
	-Wno-sign-promo

### Rules for final target.

LOCAL_LDFLAGS := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-Wl,-z,noexecstack \
	-fPIC \
	-m32 \
	-nostdlib \
	-Wl,--no-undefined \
	-Wl,--exclude-libs=ALL \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections


LOCAL_STATIC_LIBRARIES := \
	skia_skia_gyp

# Enable grouping to fix circular references
LOCAL_GROUP_STATIC_LIBRARIES := true

LOCAL_SHARED_LIBRARIES := \
	libstlport \
	libdl

# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: third_party_WebKit_Source_WebCore_WebCore_gyp_webcore_rendering_gyp

# Alias gyp target name.
.PHONY: webcore_rendering
webcore_rendering: third_party_WebKit_Source_WebCore_WebCore_gyp_webcore_rendering_gyp

include $(BUILD_STATIC_LIBRARY)
